apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ${IMAGE_NAME}
  name: ${IMAGE_NAME}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ${IMAGE_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ${IMAGE_NAME}
  name: ${IMAGE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${IMAGE_NAME}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${IMAGE_NAME}
    spec:
      containers:
        - name: ${IMAGE_NAME}
          image: ${image_tag}
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 100Mi
          env:
            - name: MTOGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-product-svc
                  key: password
            - name: MTOGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-product-svc
                  key: username
          envFrom:
            - configMapRef:
                name: mtogo-db-jdbc
